# Site
name: "Açık Veri ve Veri Gazeteciliği Derneği"
title: "Açık Veri ve Veri Gazeteciliği Derneği"
description: "Açık Veri ve Veri Gazeteciliği Derneği, Türkiye'de ifade özgürlüğü ve dijital haklar alanında çalışan bir sivil toplum örgütüdür."
logo: 'assets/images/avvg_logo.png'
favicon: 'assets/images/avvg_logo.png'
baseurl: ''
google_analytics: 'UA-168021319-1'
disqus: 'demowebsite'
mailchimp-list: 'https://avvg.us10.list-manage.com/subscribe/post?u=5390cb466c2c2cfa613a16ff4&amp;id=a7c8858d32'
include: ["_pages"]
permalink: /:title/
email: info@avvg.org.tr

# Authors
authors:
  avvg:
    name: AVVG
    display_name: Açık Veri ve Veri Gazeteciliği Derneği
    gravatar: 
    email: info@avvg.org.tr
    web: http://www.avvg.org.tr/
    twitter: https://twitter.com/AcikVeriDernegi
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

# Comments (true or false)
comments: false

# Related posts (true or false)
related-posts: false

# Show author details (true or false)
show-author: false